# -*- coding: utf-8 -*-
"""Random-forest.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1luJ1D1NgbyUqz_L-YqT3Rg4GL5MGCdnH
"""

import pandas as pd
from sklearn.datasets import load_digits
digits = load_digits()

dir(digits)

# Commented out IPython magic to ensure Python compatibility.
# %matplotlib inline
import matplotlib.pyplot as plt
plt.gray()
for i in range(5):
  plt.matshow(digits.images[i])

digits.data[:3]

df= pd.DataFrame(digits.data)
df.head()

df['target']=digits.target
df.head()

from sklearn.model_selection import train_test_split
X_train , X_test,y_train,y_test = train_test_split(df.drop(['target'],axis='columns'),digits.target,test_size=0.2)

from sklearn.ensemble import RandomForestClassifier
model = RandomForestClassifier(n_estimators=20)
model.fit(X_train,y_train)

model.score(X_test,y_test)

y_predicted = model.predict(X_test)

from sklearn.metrics import confusion_matrix
cm= confusion_matrix(y_test,y_predicted)
cm

