# -*- coding: utf-8 -*-
"""decision_tree.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1tKh0L1ZH3aG2P1TIksjWb7El0fHtjoGi
"""

import pandas as pd

df = pd.read_csv("titanic.csv")
df.head()

inputs = df.drop(['Name','Survived'],axis='columns')



inputs

target = df['Survived']

from sklearn.preprocessing import LabelEncoder
le_Sex = LabelEncoder()

inputs['Sex'] = le_Sex.fit_transform(inputs['Sex'])

inputs.Age = inputs.Age.fillna(inputs.Age.mean())

inputs

inputs_n = inputs.drop(['Sex'],axis='columns')

target

from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(inputs_n,target,test_size=0.2)

from sklearn import tree
model = tree.DecisionTreeClassifier()

model.fit(X_train, y_train)

model.score(X_test,y_test)

